# terraform/modules/vault/helm-values.yaml.tpl
#
# Vault Helm values template — rendered by Terraform templatefile().
# Do NOT edit this file directly; values are injected by main.tf at apply time.
#
# Injected variables: environment, kms_key_id, aws_region, replicas

global:
  enabled: true

server:
  image:
    tag: "1.16.2"

  # KMS auto-unseal for staging and prod.
  # Dev uses Shamir unseal — the bootstrap script handles that manually.
  # The %{ if } block means this stanza is only rendered when kms_key_id is set.
  %{ if kms_key_id != "" }
  extraConfig: |
    seal "awskms" {
      region     = "${aws_region}"
      kms_key_id = "${kms_key_id}"
    }
  %{ endif }

  # HA with Raft for staging and prod (replicas > 1)
  ha:
    enabled: ${replicas > 1 ? "true" : "false"}
    replicas: ${replicas}

    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable     = 1
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path    = "/vault/data"
          node_id = "{{ env "HOSTNAME" }}"
        }

        %{ if kms_key_id != "" }
        seal "awskms" {
          region     = "${aws_region}"
          kms_key_id = "${kms_key_id}"
        }
        %{ endif }

        service_registration "kubernetes" {}

  # Standalone config for dev (single replica, file storage, Shamir unseal)
  %{ if replicas == 1 }
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address     = "[::]:8200"
      }

      storage "file" {
        path = "/vault/data"
      }
  %{ endif }

  serviceAccount:
    create: true
    name: vault
    # IRSA annotation is applied by kubernetes_annotations resource in main.tf
    # after the Helm release completes, so it does not need to be set here.

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: gp3

  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&perfstandbyok=true"

injector:
  enabled: true
  replicas: ${replicas > 1 ? 2 : 1}

ui:
  enabled: true
  serviceType: ClusterIP
